### ISSUE TITLE
Error in installation

### ISSUE THREAD

**Issue by NervenCid** [kaltura/KalturaGeneratedAPIClientsNodeJS#11] opened 2016-09-01 01:34 UTC
Hello, i tried to install but i got this error instead:

C:\WINDOWS\system32>npm install -g kaltura
npm ERR! Windows_NT 10.0.14393
npm ERR! argv "C:\Program Files\nodejs\node.exe" "C:\Users\nerve\AppData\Roaming\npm\node_modules\npm\bin\npm-cli.js" "install" "-g" "kaltura"
npm ERR! node v6.5.0
npm ERR! npm  v3.10.6
npm ERR! code EREADFILE

npm ERR! Error extracting C:\Users\nerve\AppData\Roaming\npm-cache\fs\0.0.0\package.tgz archive: ENOENT: no such file or directory, open 'C:\Users\nerve\AppData\Roaming\npm-cache\fs\0.0.0\package.tgz'
npm ERR!
npm ERR! If you need help, you may report this error at:
npm ERR!     https://github.com/npm/npm/issues

npm ERR! Please include the following file with any support request:
npm ERR!     C:\WINDOWS\system32\npm-debug.log

How can it be fixed?

**Comment by kaltura-hooks** [comment] 2016-09-01 01:37
Hi @NervenCid,

Thank for you reporting an issue and helping improve Kaltura!

To get the fastest response time, and help the maintainers review and test your reported issues or suggestions, please ensure that your issue includes the following (please comment with more info if you have not included all this info in your original issue):
- Is the issue you're experiencing consistent and across platforms? or does it only happens on certain conditions?
  please provide as much details as possible.
- Which Kaltura deployment you're using: Kaltura SaaS, or self-hosted?
  If self hosted, are you using the RPM or deb install?
- Packages installed.
  When using RPM, paste the output for:

```
    # rpm -qa \"kaltura*\"
```

```
For deb based systems:
```

```
    # dpkg -l \"kaltura-*\"
```
- If running a self hosted ENV - provide the MySQL server version used
- If running a self hosted ENV - is this a single all in 1 server or a cluster?
- If running a self hosted ENV, while making the problematic request, run:

```
    # tail -f /opt/kaltura/log/*.log /opt/kaltura/log/batch/*.log | grep -A 1 -B 1 --color \"ERR:\|PHP\|trace\|CRIT\|\[error\]\"
```

   and paste the output.
- When relevant, provide any screenshots or screen recordings showing the issue you're experiencing.

For general troubleshooting see:
https://github.com/kaltura/platform-install-packages/blob/Jupiter-10.13.0/doc/kaltura-packages-faq.md#troubleshooting-help

If you only have a general question rather than a bug report, please close this issue and post at:
http://forum.kaltura.org

Thank you in advance,

**Comment by NervenCid** [comment] 2016-09-01 02:09
Thank you for your answer @kaltura-hooks  :+1: 

I'm installing kaltura with the comand

npm install -g kaltura

I'm using nodejs 6.5.0 with windows 10 enviroment

**Comment by jiintac** [comment] 2016-10-07 04:01
Hi, i'm having the same issue.

@NervenCid  have you installed it?

**Comment by jessp01** [comment] 2016-10-07 12:37
Hello,

Your error does not seem related to the kaltura package specifically. Are you able to install other packages?
Regardless, you can just download this archive https://github.com/kaltura/KalturaGeneratedAPIClientsNodeJS/archive/master.zip, extract it and try to run:

```
npm install
```

inside the root dir.

**Comment by jiintac** [comment] 2016-10-10 01:15
hi @jessp01 I can install other packages. I also did npm cache just to make sure but i still can't install it using npm. I'll try the one you gave. Thank you very much!

**Comment by jiintac** [comment] 2016-10-10 01:23
Hi @jessp01, i tried doing the npm install, same error :(

**Comment by Brunissimo** [comment] 2016-10-10 11:58
Hi @jessp01 ,

I've installed kaltura package several times for other projects but this time when I try to install it via 
**git clone https://github.com/kaltura/KalturaGeneratedAPIClientsNodeJS.git** and
**npm install** 

or simply,
**npm install kaltura**

I get this error:

`(node:29103) fs: re-evaluating native module sources is not supported. If you are using the graceful-fs module, please update it to a more recent version.`
`npm ERR! Linux 3.13.0-32-generic`
`npm ERR! argv "/usr/local/bin/node" "/usr/local/bin/npm" "install"`
`npm ERR! node v6.7.0`
`npm ERR! npm  v3.10.3`
`npm ERR! code EREADFILE`

`npm ERR! Error extracting /root/.npm/fs/0.0.0/package.tgz archive: ENOENT: no such file or directory, open '/root/.npm/fs/0.0.0/package.tgz'`
`npm ERR!`
`npm ERR! If you need help, you may report this error at:`
`npm ERR!     <https://github.com/npm/npm/issues>`

`npm ERR! Please include the following file with any support request:`
`npm ERR!     /root/kaltura/nodeServerCookie/KalturaGeneratedAPIClientsNodeJS-master/npm-debug.log`

Do you have any idea what it could be? It's strange because I'0ve already used this several times but it doesn't work now. (I'm able to install other packages without any issues.)

Many thanks

**Comment by jessp01** [comment] 2016-10-10 15:17
Hi @Brunissimo,

I was unable to reproduce it but then noticed you're using node v6.7.0, when using the same, I got the same error.  Try editing package.json in the clone and change:

```
"fs": "*",
```

to:

```
"fs": "0.0.1-security",
```

then try npm install again..

This worked correctly for me. Do let me know.

**Comment by Brunissimo** [comment] 2016-10-10 15:37
Thanks a lot. It worked. :)

**Comment by jessp01** [comment] 2016-10-10 15:47
Good. I'll release a new NPM that includes this change. Quite strange that this is an issue from the get go since it works fine with NodeJS 4 but since this fix will make it work for both, I have no objection:)

Thanks for reporting back,

**Closed as completed by jessp01** 2016-10-10 15:47 UTC

**Comment by jessp01** [comment] 2016-10-10 16:13
Released version 3.3.3 so `npm install kaltura` should work correctly with the NPM that comes with Node 6.7 as well.

**Comment by jiintac** [comment] 2016-10-11 01:21
hi @jessp01, thank you very much!

**Comment by jessp01** [comment] 2016-10-11 14:05
@aquiintac - most welcome.
Please also see https://github.com/kaltura/KalturaGeneratedAPIClientsNodeJS/pull/12 and specifically http://status.npmjs.org/incidents/dw8cr1lwxkcr. Seems the fs module should not be required at all. We shall be releasing a new version without it soon but it should be fine to use 3.3.3 in the meantime.

**Comment by lostandfownd** [comment] 2017-10-06 09:32
@jessp01 worked , thank you
